### ISSUE TITLE
small graphical errors using HDMI and flip screen switch

### ISSUE THREAD

**Issue by alienator303** [nullobject/Arcade-Cave_MiSTer#22]
Mister setup: 128mb

The players laserbeam has small graphical glitches when using the flip screen switch on hdmi. (pic 1/2)
(here on the green beam) https://ibb.co/xC59993
('red' ship firing its laser)  https://ibb.co/2c7qw1H
 
They are not there when running in its original orientation.

however, when switching back to original orientation it seems to produce more glitches (last pic) 
But only after the flip orientation toggle.
https://ibb.co/kSYBSSb

Hope this helps out figuring out this problem!

**Comment by Saroumane** [comment]
I can confirm the problem with my CRTs.
I have to activate "Flip screen : On" and then I see the same ligne glitch :
![IMG_20210105_093349](https://user-images.githubusercontent.com/22261137/103624782-50f71680-4f3a-11eb-8010-cf5dc4f0d8a5.jpg)
![IMG_20210105_093437](https://user-images.githubusercontent.com/22261137/103624864-72580280-4f3a-11eb-89ef-d49dbfffb290.jpg)

**Comment by nullobject** [comment]
@alienator303 @Saroumane Thanks for the screenshots. I can defintely reproduce the problem on my setup, so I will try to fix it ASAP.

**Comment by felleg** [comment]
Just wanted to chime in and say, I'm using the flipped orientation as well, and I notice the issue is not limited to the player's laser, on the same row pixels also get garbbled.
![IMG_20210111_123252](https://user-images.githubusercontent.com/7781739/104217810-da5e8b00-5409-11eb-980d-fd78a6cc00be.jpeg)
(using the no-warning.mra, TATE mode, flipped, beta 6)

**Comment by nullobject** [comment]
This has been fixed.

It turned out to be a sprite clipping issue, thanks for reporting it :+1:
