### ISSUE TITLE
MRA loading

### ISSUE THREAD

**Issue by akerasi** [nullobject/Arcade-Cave_MiSTer#7]
I tried, as an experiment, to write up an MRA for Fever SOS (chosen at random from other Cave Gen1 games) to see what would happen; I didn't expect it to work, and it didn't, but what happened was truly odd; it seemed to ignore completely the contents of the MRA I'd written, and correctly loaded and played Dodonpachi. Even tried it with just my custom MRA, no Dodonpachi MRA on the MiSTer, and cold booted; still correctly loaded Dodonpachi, rather than tried at all to load Fever SOS. I realize this isn't really an issue with what this version is trying to do, but the fact it's completely ignoring what's written in the MRA is likely useful info, and might lead to figuring some things out, especially when you do get to adding other games to the core.

**Comment by nullobject** [comment]
That's quite odd. There are some differences between the Cave 68K games (memory map, GPU, etc.), so it would be very unlikely for another MRA file to work without any changes to the core.

But I wouldn't expect DDP to boot up without any issue when loading another MRA, so that is defintely odd.

Currently, the core doesn't use the SDRAM module — everything is done in the DDR3 memory — so it is totally possible for the DDP ROMs to stick around in DDR3, even after a hard reset. That may explain part of what is going on here :thinking:

**Comment by akerasi** [comment]
Tried it again, with a truly fresh boot, and it just does nothing, as expected; I think your hypothesis about DDP sticking in DDR3 memory must be the correct one. Still seems strange that it didn't even try to load what I put in the MRA though... I've attached it, in case it's useful.
[FeverSOS.zip](https://github.com/nullobject/Arcade-Cave_MiSTer/files/5079904/FeverSOS.zip)
